spring.application.name=backend-spring
server.port=4000
spring.web.resources.static-locations=file:../frontend/,classpath:/static/
spring.mvc.static-path-pattern=/**
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:whiteboarddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
